url: "https://quartersbrief.github.io"
title: "quartersbrief"
# baseurl must be empty instead of just omitting it; see https://github.com/github/pages-gem/issues/359
baseurl: '' 

repository: BadIdeaException/quartersbrief

plugins:
  - "jekyll-github-metadata"

include:
  - _pages

defaults:
  -
    scope:
      path: "_pages"
    values:
      permalink: "/:title:output_ext"