url: "https://quartersbrief.github.io"
title: "quartersbrief"
# baseurl must be empty instead of just omitting it; see https://github.com/github/pages-gem/issues/359
baseurl: '' 

repository: quartersbrief/quartersbrief

plugins:
  - jekyll-github-metadata
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
  
include:
  - _pages

defaults:
  -
    scope:
      path: "_pages"
    values:
      permalink: "/:basename:output_ext"